spring.application.name=springWithJdbcTemplate

spring.datasource.url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.username=SYSDBA
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

##test db2
spring.datasource.db2.url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db2.username=SYSDBA
spring.datasource.db2.password=masterkey
spring.datasource.db2.driver-class-name=org.firebirdsql.jdbc.FBDriver

# connection pool (default = Hikari)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
# Suitable for firebirdsql to tuning speed
spring.datasource.hikari.auto-commit=false
