spring.application.name=springWithJdbcTemplate
spring.threads.virtual.enabled=true
logging.level.org.springframework.web.servlet.resource=WARN

##primary db
spring.datasource.url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.username=SYSDBA
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
# connection pool (default = Hikari)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
# Suitable for firebirdsql to tuning speed
spring.datasource.hikari.auto-commit=false

##test db2 ,use .jdbc-url for db2,db3,... . for first db spring auto map .url to .jdbc-url
spring.datasource.db2.jdbc-url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db2.username=SYSDBA
spring.datasource.db2.password=masterkey
spring.datasource.db2.driver-class-name=org.firebirdsql.jdbc.FBDriver
# connection pool (default = Hikari)
spring.datasource.db2.hikari.maximum-pool-size=10
spring.datasource.db2.hikari.minimum-idle=2
spring.datasource.db2.hikari.connection-timeout=30000
# Suitable for firebirdsql to tuning speed
spring.datasource.db2.hikari.auto-commit=false

