spring.application.name=springWithJdbcTemplate
spring.threads.virtual.enabled=true

#รูปแบบปกติถ้าใช้ database อันเดียว จากการทดสอบใช้คู่กับแบบ multi-datasoure ยุ่งยาก
#spring.datasource.url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
#spring.datasource.username=SYSDBA
#spring.datasource.password=masterkey
#spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
#spring.datasource.hikari.maximum-pool-size=3
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.auto-commit=false

##primary db (ใช้พารามิเตอร์ Hikari โดยตรง)
spring.datasource.db1.jdbc-url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db1.username=SYSDBA
spring.datasource.db1.password=masterkey
spring.datasource.db1.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.db1.maximum-pool-size=3
spring.datasource.db1.minimum-idle=2
spring.datasource.db1.connection-timeout=30000
# Suitable for firebirdsql to tuning speed
spring.datasource.db1.auto-commit=false

##test db2
spring.datasource.db2.jdbc-url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db2.username=SYSDBA
spring.datasource.db2.password=masterkey
spring.datasource.db2.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.db2.maximum-pool-size=3
spring.datasource.db2.minimum-idle=2
spring.datasource.db2.connection-timeout=30000
# Suitable for firebirdsql to tuning speed
spring.datasource.db2.auto-commit=false

